apiVersion: v1
kind: Template
labels:
  template: build-logs-aggregation-imagestream
  thoth: 0.1.0
metadata:
  name: build-logs-aggregation-imagestream
  annotations:
    description: This is Thoth Core - build-logs-aggregation
    openshift.io/display-name: "Thoth: build-logs-aggregation"
    version: 0.1.3
    tags: poc,thoth,ai-stacks,package-extract
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth Package
      Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: build-logs-aggregation-base
  spec:
    name: latest
    lookupPolicy:
      local: true

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: build-logs-aggregation-job
  spec:
    name: latest
    lookupPolicy:
      local: true
